---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: {{ CLUSTER_NAME }}
  labels:
    cni: {% if WINDOWS %}flannel-windows{% else %}calico{% endif %}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - {% if WINDOWS %}10.244.0.0/16{% else %}192.168.0.0/16{% endif %}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: AzureCluster
    name: {{ CLUSTER_NAME }}
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    name: {{ CLUSTER_NAME }}-control-plane
