---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ CLUSTER_NAME }}
  labels:
    {%- if WINDOWS %}
    cni: calico
    csi-proxy: enabled
    windows: enabled
    {%- else %}
    cni: calico
    {%- endif %}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - {% if WINDOWS %}11.244.0.0/16{% else %}192.168.0.0/16{% endif %}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureCluster
    name: {{ CLUSTER_NAME }}
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: {{ CLUSTER_NAME }}-control-plane
