---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ CLUSTER_NAME }}-{{ SUFFIX }}
spec:
  template:
    spec:
      {%- if WINDOWS %}
      users:
      - name: capi
        groups: Administrators
        {%- if AZURE_SSH_PUBLIC_KEY %}
        sshAuthorizedKeys:
        - {{AZURE_SSH_PUBLIC_KEY}}
        {%- endif %}
      preKubeadmCommands: []
      postKubeadmCommands:
        - nssm set kubelet start SERVICE_AUTO_START
        - powershell C:/defender-exclude-calico.ps1
      {%- endif %}
      joinConfiguration:
        nodeRegistration:
          name: {% raw %}'{{ ds.meta_data["local_hostname"] }}'{% endraw %}
          {%- if WINDOWS %}
          criSocket: npipe:////./pipe/containerd-containerd
          {%- endif %}
          kubeletExtraArgs:
            azure-container-registry-config: {% if WINDOWS %}c:/k/azure.json{% else %}/etc/kubernetes/azure.json{% endif %}
            cloud-provider: {% if EXTERNAL_CLOUD_PROVIDER %}external{% else %}azure{% endif %}
            {%- if WINDOWS %}
            cloud-config: c:/k/azure.json
            feature-gates: "WindowsHostProcessContainers=true"
            v: "2"
            windows-priorityclass: "ABOVE_NORMAL_PRIORITY_CLASS"
            {%- else %}
            cloud-config: /etc/kubernetes/azure.json
            {%- endif %}
      files:
      - contentFrom:
          secret:
            name: {{ CLUSTER_NAME }}-{{ SUFFIX }}-azure-json
            key: worker-node-azure.json
        owner: root:root
        path: {% if WINDOWS %}c:/k/azure.json{% else %}/etc/kubernetes/azure.json{% endif %}
        permissions: "0644"
      {%- if WINDOWS %}
      - path: C:/defender-exclude-calico.ps1
        permissions: "0744"
        content: |-
          Add-MpPreference -ExclusionProcess C:/opt/cni/bin/calico.exe
          Add-MpPreference -ExclusionProcess C:/opt/cni/bin/calico-ipam.exe
      {%- endif %}
