---
apiVersion: exp.cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: {{ CLUSTER_NAME }}-{{ SUFFIX }}
spec:
  clusterName: {{ CLUSTER_NAME }}
  replicas: {{ WORKER_MACHINE_COUNT }}
  template:
    spec:
      clusterName: {{ CLUSTER_NAME }}
      version: {{ KUBERNETES_VERSION }}
      bootstrap:
        configRef:
          name: {{ CLUSTER_NAME }}-{{ SUFFIX }}
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfig
      infrastructureRef:
        name: {{ CLUSTER_NAME }}-{{ SUFFIX }}
        apiVersion: exp.infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureMachinePool
