name: az-capi-nightly

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '45 0 * * *' # Every day at 00:45 UTC
  workflow_dispatch:

env:
  IMAGE: Azure/azure-capi-cli-extension

permissions:
  contents: read

jobs:

  build:
    name: Build
    permissions:
      contents: write  # for pyTooling/releaser to create a release
      packages: write  # for pyTooling/releaser to upload a package
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate

        python -m pip install -U pip
        python -m pip install -r requirements.txt
        azdev setup --repo . --ext capi

    - name: Build extension
      run: |
        source env/bin/activate

        # set to vnext for versioning
        sed -i "s/VERSION = '.*'/VERSION = '0.0.vnext'/g" src/capi/setup.py
        azdev extension build capi

        WHEEL=$(find ./dist -name "*.whl" -printf "%f")
        echo "WHEEL=$WHEEL" >> $GITHUB_ENV

    # sometimes eine/tip@master fails to upload release artifacts and this leaves
    # a stale tmp file on the release which causes future runs of this workflow to fail.
    - name: delete tmp.* release artifacts
      uses: mknejp/delete-release-assets@ea7ff12c30ef2589fe4311264f3a336d01325030 # v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: az-capi-nightly
        fail-if-no-assets: false # do not fail if does not exist
        assets: tmp.${{ env.WHEEL }}

    - uses: pyTooling/Actions/releaser@f11c3356740c953df7983fe299290a1499f3399e # r0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: az-capi-nightly
        files: |
          dist/${{ env.WHEEL }}
